services:
  backend:
    image: 940075379174.dkr.ecr.us-east-1.amazonaws.com/calculadora/backend:${APP_VERSION:latest}
    expose:
      - 8000
    environment:
      - ENVIRONMENT=dev
      - ALLOWED_ORIGINS=http://localhost
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app
  frontend:
    image: 940075379174.dkr.ecr.us-east-1.amazonaws.com/calculadora/frontend:${APP_VERSION:latest}
    ports:
      - "80:80"
    environment:
      BACKEND_HOST=backend
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app

networks:
  app: