apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: calculator
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
      component: backend
  template:
    metadata:
      labels:
        app: calculator
        component: backend
    spec:
      containers:
        - name: backend
          image: 940075379174.dkr.ecr.us-east-1.amazonaws.com/calculadora/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENVIRONMENT
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ALLOWED_ORIGINS
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: LOG_LEVEL
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
